AllCops:
  TargetRubyVersion: 2.3
  DisabledByDefault: true
  Exclude:
    - rake.gemspec

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/HashSyntax:
  Enabled: true

LineLength:
  Enabled: true
  Max: 120

WhileUntilModifier:
  Enabled: false

IfUnlessModifier:
  Enabled: false
