AllCops:
  TargetRubyVersion: 2.3
  DisabledByDefault: true
  Exclude:
    - rake.gemspec

LineLength:
  Enabled: true
  Max: 120

Style/HashSyntax:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

SpaceAroundEqualsInParameterDefault:
  Enabled: false

WhileUntilModifier:
  Enabled: false

IfUnlessModifier:
  Enabled: false
