---
after_script:
- ruby -Ilib bin/rake travis:after -t
before_script:
- gem install hoe-travis --no-document
- gem install minitest -v '~> 5.0' --no-document
- ruby -Ilib bin/rake travis:before -t
language: ruby
sudo: false
notifications:
  email:
  - drbrain@segment7.net
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.1
  - ruby-head
  - jruby
  - rbx-2
script: ruby -Ilib bin/rake
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
