language: ruby
rvm:
  - ruby-head
  - jruby-9.2.4.0
  - jruby-head

matrix:
  include:
    - rvm: ruby-head
      env: COVERALLS=yes

before_script:
  - unset JRUBY_OPTS
  - unset _JAVA_OPTIONS
  - if ruby -e "exit RUBY_VERSION >= '2.3.0'"; then gem update --system=3.0.1; else gem update --system=2.7.8; fi

script: ruby -Ilib exe/rake
