name: windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby: [ '2.6.x', '2.5.x', '2.4.x' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        gem install minitest
        ruby -Ilib exe/rake
